name: TOOLBOXLAP

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Download and Install Playit
        run: |
          Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
          Start-Sleep -Seconds 5

      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "admin@123" -Force)

      - name: Start Playit Tunnel
        run: |
          $authKey = "7dcb5daa1b7bd7319d36e0ba18ae0f0ef79c6de807e789ec5524d3c3b9189a2e"
          Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $authKey" -NoNewWindow
          Start-Sleep -Seconds 5
          Start-Process -FilePath "$env:USERPROFILE\playit.exe" -NoNewWindow

      - name: Keep the GitHub Action Runner Alive
        run: Start-Sleep -Seconds 21600
